services:
  app:
    image: monnashahul/spring-mongodb-rest
    ports: ['8080:8080']
    restart: always
    depends_on: [mongo]
  mongo:
    image: mongo
    ports: ['27017:27017']
    restart: always
  mongo-express:
    image: mongo-express
    ports: ['8081:8081']
    restart: always
version: '3.1'
